import React, { useState } from 'react';
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Theme from '@/Components/Theme'
import MainContent from '@/Components/mainContent'
import Check from '@/Components/check';
import { AskCheck } from '@/Interfaces/askCheck';
import instaLogo from '/public/images/instaLogo.png';
import Image from 'next/image'

const Home: React.FC = () => {
  const [ isCheck, setCheck ] = useState(false);
  const [ showAsk, setAsk ] = useState({} as AskCheck);

  const handleOpenCheck = (checkButton: string) => {
    if (checkButton === 'in') {
      setAsk({
        title: 'CHECKING',
        subTitle: 'Que bom que você veio!',
        ask: 'Quero muito saber, como você está chegando hoje?'
      });

      return setCheck(true);
    }

    setAsk({
      title: 'CHECKOUT',
      subTitle: 'Ufa, acabou...',
      ask: 'Depois dessa aula,  como você está saindo?'
    });

    return setCheck(true);
  }

  return (
    <>
      <Head>
        <title>Talipep Run</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Theme>
          {!isCheck && <MainContent openCheck={handleOpenCheck}/>}
          {isCheck && <Check formSentences={showAsk} backMain={setCheck} />}
        </Theme>
      </main>
      <footer className={styles.footer}>
        <div>
          <a 
            className={styles.socialMedia} 
            href='https://encurtador.com.br/lnoP2' 
            target='_blank'
          >
            <Image
              src={instaLogo}
              alt='Instagram da Talipep'
              width={40}
              style={{ marginRight: '0.5rem' }}
              priority
            />
            <span>
              Instagram da Talipep
            </span>              
          </a>
        </div>

        <div className={styles.rights}>
          All Rights Reserved by Isac Chuab
        </div>
      </footer>
    </>
  )
}

export default Home;
//talitavieira333@gmail.com template_mhc8k4i
/*Olá Pep, estou fazendo o {{title}}

Sou o Aluno(a): {{user}},
Meu E-mail é: {{email}},
Estou me sentindo: {{feelingOptions}}

Att. {{user}}*/